name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: set NDK
      shell: bash
      run: |
        set -x
        echo "ANDROID_NDK=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV


    - name: Build with Gradle
      run: |
        ./gradlew --info \
          -PsigningStorePassword="${{ secrets.SIGNING_STORE_PASSWORD }}" \
          -PsigningKeyAlias="${{ secrets.SIGNING_KEY_ALIAS }}" \
          -PsigningKeyPassword="${{ secrets.SIGNING_KEY_PASSWORD }}" \
          assembleFDroidRelease bundleFDroidRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: smartautoclicker-release
        path: smartautoclicker/build/outputs/
